package:
  name: cuda-compiler
  version: 12.0.0

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 0
  noarch: generic

requirements:
  run:
    - __{{ noarch_platforms }}
    - c-compiler
    - cxx-compiler
    - cuda-cuobjdump 12.0.76
    - cuda-cuxxfilt 12.0.76
    - cuda-nvcc 12.0.76
    - cuda-nvprune 12.0.76

test:
  commands:
    - which cuobjdump  # [linux]
    - which cu++filt   # [linux]
    - which nvcc       # [linux]
    - which nvprune    # [linux]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: A meta-package containing tools to start developing a CUDA application
  description: |
    A meta-package containing tools to start developing and compiling a
    basic CUDA application.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - adibbley
