{% set version = "13.0.2" %}
{% set exists = "" %}  # [not (linux or win)]
{% set exists = "which" %}  # [linux]
{% set exists = "where" %}  # [win]

package:
  name: cuda-compiler
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  # This is 'technically' not a noarch package: only supported on linux-64, linux-aarch64 and windows-64
  # Therefore, 'noarch: generic' is replaced with 'skip: true' to avoid building on unsupported platforms.
  skip: true  # [osx]

requirements:
  run:
    # Remove '__linux' and '__win' as they might not be handled properly on PBP
    # Also, see above note about 'skip: true'
    - c-compiler
    - cxx-compiler
    - cuda-cuobjdump 13.0.85
    - cuda-cuxxfilt 13.0.85
    - cuda-nvcc 13.0.88
    - cuda-nvprune 13.0.85
    - cuda-ctadvisor 13.0.85

test:
  commands:
    - {{ exists }} cuobjdump
    - {{ exists }} cu++filt
    - {{ exists }} nvcc
    - {{ exists }} nvprune
    - {{ exists }} ctadvisor

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: A meta-package containing tools to start developing a CUDA application
  description: |
    A meta-package containing tools to start developing and compiling a
    basic CUDA application.
  doc_url: https://docs.nvidia.com/cuda/index.html
  dev_url: https://docs.nvidia.com/cuda/index.html

extra:
  skip-lints:
    - license_file_overspecified
  recipe-maintainers:
    - conda-forge/cuda
